-- Insertar 50 registros en la tabla tasks
INSERT INTO tasks (title, description, status)
VALUES
('Desarrollar una aplicación web con React', 'Crear una aplicación web utilizando React.js y componentes reutilizables', 'En proceso'),
('Implementar un sistema de autenticación con JWT', 'Desarrollar un sistema de autenticación seguro utilizando JSON Web Tokens (JWT)', 'Pendiente'),
('Optimizar el rendimiento de una base de datos', 'Realizar ajustes y optimizaciones en una base de datos para mejorar su rendimiento', 'Pendiente'),
('Crear un bot de Telegram con Python', 'Desarrollar un bot para la plataforma de mensajería Telegram utilizando Python y la API de Telegram', 'Bloqueado'),
('Diseñar la interfaz de usuario de una aplicación móvil', 'Diseñar la interfaz de usuario (UI) de una aplicación móvil utilizando herramientas como Sketch o Figma', 'En proceso'),
('Resolver problemas de seguridad en una aplicación web', 'Identificar y solucionar vulnerabilidades de seguridad en una aplicación web', 'Pendiente'),
('Desplegar una aplicación en un servidor AWS', 'Configurar y desplegar una aplicación web en un servidor de Amazon Web Services (AWS)', 'Completado'),
('Implementar un algoritmo de ordenamiento en C++', 'Desarrollar un algoritmo de ordenamiento eficiente utilizando el lenguaje de programación C++', 'Pendiente'),
('Crear un sistema de gestión de tareas con Laravel', 'Desarrollar un sistema web de gestión de tareas utilizando el framework PHP Laravel', 'En proceso'),
('Desarrollar un chatbot con inteligencia artificial', 'Crear un chatbot capaz de comprender y responder preguntas utilizando técnicas de inteligencia artificial y procesamiento de lenguaje natural', 'En proceso'),
('Optimizar el rendimiento de un sitio web', 'Realizar mejoras en el rendimiento de un sitio web para reducir el tiempo de carga y mejorar la experiencia del usuario', 'Pendiente'),
('Diseñar una base de datos relacional', 'Diseñar la estructura de una base de datos relacional teniendo en cuenta los requisitos del sistema', 'Completado'),
('Crear una aplicación móvil con Flutter', 'Desarrollar una aplicación móvil multiplataforma utilizando el framework Flutter de Google', 'Bloqueado'),
('Implementar un sistema de control de versiones con Git', 'Configurar un repositorio de Git y aprender a utilizar comandos básicos para controlar versiones de código fuente', 'En proceso'),
('Desarrollar un sitio web estático con HTML y CSS', 'Crear un sitio web estático utilizando únicamente HTML y CSS, sin la necesidad de un servidor backend', 'Pendiente'),
('Realizar pruebas de unidad en un proyecto Java', 'Escribir y ejecutar pruebas de unidad para verificar el comportamiento de clases y métodos en un proyecto Java', 'Completado'),
('Implementar un sistema de recomendaciones con Python', 'Desarrollar un sistema de recomendaciones utilizando algoritmos de aprendizaje automático y el lenguaje de programación Python', 'En proceso'),
('Crear un juego en 2D con Unity', 'Desarrollar un juego en dos dimensiones utilizando el motor de juego Unity y lenguaje de programación C#', 'Pendiente'),
('Diseñar la arquitectura de un sistema distribuido', 'Diseñar la arquitectura de un sistema distribuido teniendo en cuenta aspectos como escalabilidad, disponibilidad y tolerancia a fallos', 'Pendiente'),
('Desarrollar un plugin para WordPress', 'Crear un complemento personalizado para el popular sistema de gestión de contenidos (CMS) WordPress utilizando PHP y JavaScript', 'En proceso'),
('Optimizar el código de un proyecto PHP', 'Refactorizar y optimizar el código de un proyecto PHP para mejorar su legibilidad, rendimiento y mantenibilidad', 'Completado'),
('Implementar autenticación OAuth en una aplicación web', 'Integrar el protocolo OAuth en una aplicación web para permitir que los usuarios inicien sesión utilizando sus cuentas de redes sociales', 'Bloqueado'),
('Crear un servicio de API RESTful con Node.js', 'Desarrollar un servicio web que siga el estilo de arquitectura REST utilizando el entorno de ejecución JavaScript Node.js', 'En proceso'),
('Diseñar la arquitectura de microservicios de una aplicación', 'Definir la estructura y comunicación entre los microservicios que componen una aplicación basada en arquitectura de microservicios', 'Pendiente'),
('Desarrollar un sistema de recomendación de productos', 'Implementar un sistema de recomendación personalizado para un sitio de comercio electrónico utilizando técnicas de filtrado colaborativo y aprendizaje automático', 'En proceso'),
('Optimizar consultas SQL en una base de datos MySQL', 'Analizar y mejorar el rendimiento de consultas SQL en una base de datos MySQL mediante técnicas de indexación y optimización de consultas', 'Pendiente'),
('Crear un dashboard interactivo con React y Chart.js', 'Desarrollar un panel de control interactivo utilizando React.js para la interfaz de usuario y Chart.js para la visualización de datos', 'Completado'),
('Implementar un sistema de gestión de usuarios con Django', 'Crear un sistema de gestión de usuarios y permisos utilizando el framework de desarrollo web Django en Python', 'En proceso'),
('Desarrollar un algoritmo de aprendizaje automático en R', 'Implementar un algoritmo de aprendizaje automático utilizando el lenguaje de programación R y sus bibliotecas especializadas', 'Bloqueado'),
('Configurar un servidor de correo electrónico con Postfix', 'Instalar y configurar el servidor de correo electrónico Postfix en un sistema Linux para enviar y recibir mensajes de correo electrónico de manera segura y eficiente', 'En proceso'),
('Diseñar la interfaz de usuario de una aplicación móvil', 'Crear un diseño intuitivo y atractivo para la interfaz de usuario de una aplicación móvil utilizando herramientas de diseño como Adobe XD o Sketch', 'Pendiente'),
('Desarrollar una aplicación web progresiva (PWA)', 'Crear una aplicación web progresiva que funcione sin conexión y proporcione una experiencia de usuario similar a la de una aplicación nativa en dispositivos móviles', 'Completado'),
('Implementar un sistema de cola de mensajes con RabbitMQ', 'Configurar y utilizar RabbitMQ como sistema de mensajería para implementar una arquitectura de microservicios basada en colas', 'En proceso')

